### ISSUE TITLE
How to enable elasticsearch query logging?

### ISSUE THREAD

**Issue by tback** [Benoss/django-elasticsearch-debug-toolbar#3]
My elasticpanel outputs:
Elastic Queries

DEBUG is set to False. This means that Elastic query logging is disabled. 

the DEBUG setting of my django project is set to true.

Thanks for your help

**Comment by Benoss** [comment]
Are the other Debug toolbar modules working?

**Comment by tback** [comment]
Yes they are. I tested on cpython 2.7.6 and PyPy 2.4.0 (python 3.2.5).

**Comment by Benoss** [comment]
Have not migrated yet to Django 1.8 will test tomorrow

**Comment by Benoss** [comment]
Tested on 1.8 it is working, I don't know what is your issue

**Comment by timb07** [comment]
I encountered the same error message of "DEBUG is set to False. This means that Elastic query logging is disabled." even though DEBUG was True.

I suspect it's because the template is checking the value of "debug", but that doesn't seem to be set in the context.

Note that when there are actually search results to report on, the error is not displayed, and it seems to be working fine.

Adding this note here in case anyone else comes across this situation.
